vault:
    host: ${CONSUL_HOST}
    port: ${CONSUL_PORT}
    scheme: ${CONSUL_SCHEME}
    token: ${CONSUL_TOKEN}
    path: ${CONSUL_PATH}
consul:
    host: ${VAULT_HOST}
    port: ${VAULT_PORT}
    scheme: ${VAULT_SCHEME}
    token: ${VAULT_TOKEN}
    path: ${VAULT_PATH}
logconfig:
    mode: ${LOG_MOE}
    source_type: ${LOG_TYPE}
    source_location: ${LOG_LOCATION}
